version: '3'

tasks:
  default:
    cmds:
      - cargo run
    silent: true

  debug:
    cmds: 
      - cargo build
      - rust-gdb target/debug/gb
    silent: true

  release:
    cmds: 
      - cargo build --release
    silent: true

  test:
    cmds: 
      - cargo test
    silent: true

  clippy:
    cmds:
      - cargo clippy --fix
      - cargo fmt

  clippy_check:
    cmds:
      - cargo clippy -- -D warnings
