version: '3'

tasks:
  default:
    cmds:
      - cargo run
    silent: true

  debug:
    cmds: 
      - cargo build
      - rust-gdb --args target/debug/gb etc/cpu_instrs.gb
    silent: true

  cpu:
    cmds:
      - cargo run etc/cpu_instrs.gb

  release:
    cmds: 
      - cargo build --release
    silent: true

  test:
    cmds: 
      - cargo test
    silent: true

  clippy:
    cmds:
      - cargo fmt
      - cargo clippy

  clippy_check:
    cmds:
      - cargo clippy -- -D warnings
