version: '3'

tasks:
  default:
    cmds:
      - cargo run
    silent: true

  debug:
    cmds: 
      - cargo build
    silent: true

  debug-cpu:
    cmds:
      - task debug
      - rust-gdb --args target/debug/gb etc/cpu_instrs.gb
    env:
      LOG_LEVEL: "DEBUG"

  debug-ppu:
    cmds:
      - task debug
      - rust-gdb --args target/debug/gb etc/dmg-acid2.gb
    env:
      LOG_LEVEL: "DEBUG"

  cpu:
    cmds:
      - cargo run etc/cpu_instrs.gb

  ppu:
    cmds:
      - cargo run etc/dmg-acid2.gb

  release:
    cmds: 
      - cargo build --release
    silent: true

  test:
    cmds: 
      - cargo test
    silent: true

  clippy:
    cmds:
      - cargo fmt
      - cargo clippy

  clippy_check:
    cmds:
      - cargo clippy -- -D warnings
