use super::arithmetictarget::ArithmeticTarget;
use super::flagsregister::FlagsRegister;

pub enum JumpTest {
    Zero,
    NotZero,
    Carry,
    NotCarry,
    Always,
}

impl JumpTest {
    pub fn evaluate(&self, f : &FlagsRegister) -> bool {
        match self {
            JumpTest::Zero => f.zero(),
            JumpTest::NotZero => !f.zero(),
            JumpTest::Carry => f.carry(),
            JumpTest::NotCarry => !f.carry(),
            JumpTest::Always => true,
        }
    }
}

pub enum JumpType {
    Relative8,
    Relative16,
    Pointer8,
    Pointer16,

}

pub enum Instruction{
    Nop,
    Adc(ArithmeticTarget),
    Add(ArithmeticTarget),
    AddHL(ArithmeticTarget),
    And(ArithmeticTarget),
    Ccf(ArithmeticTarget),
    Cp(ArithmeticTarget),
    Cpl(ArithmeticTarget),
    Dec(ArithmeticTarget),
    Inc(ArithmeticTarget),
    Or(ArithmeticTarget),
    Rla(ArithmeticTarget),
    Rlc(ArithmeticTarget),
    Rl(ArithmeticTarget),
    Rr(ArithmeticTarget),
    Rra(ArithmeticTarget),
    Rrc(ArithmeticTarget),
    Rrca(ArithmeticTarget),
    Rrla(ArithmeticTarget),
    Sbc(ArithmeticTarget),
    Scf(ArithmeticTarget),
    Sla(ArithmeticTarget),
    Sra(ArithmeticTarget),
    Srl(ArithmeticTarget),
    Sub(ArithmeticTarget),
    Swap(ArithmeticTarget),
    Xor(ArithmeticTarget),
    // target, source
    Load(ArithmeticTarget, ArithmeticTarget),
    Load8(ArithmeticTarget),
    Load16(ArithmeticTarget),
    // target, source
    LoadH(ArithmeticTarget, ArithmeticTarget),
    // source register
    LoadH8(ArithmeticTarget),

    // Jump
    Jump(JumpTest, JumpType),

    // Calling function / Stack
    Push(ArithmeticTarget),
    Pop(ArithmeticTarget),
    Call(JumpTest),
    Ret(JumpTest),

    // target, byte to set
    Bit(ArithmeticTarget, u8),
    Set(ArithmeticTarget, u8),
    Res(ArithmeticTarget, u8),
    Halt,
}

impl Instruction {
    pub fn from_byte(byte: u8) -> Option<Instruction> {
        match byte {
            0x00 => Some(Instruction::Nop), 
            0x01 => unimplemented!("0x{:x}", byte),
            0x02 => Some(Instruction::Load16(ArithmeticTarget::BC)),
            0x03 => unimplemented!("0x{:x}", byte),
            0x04 => Some(Instruction::Inc(ArithmeticTarget::B)),
            0x05 => Some(Instruction::Dec(ArithmeticTarget::B)),
            0x06 => Some(Instruction::Load8(ArithmeticTarget::B)), 
            0x07 => unimplemented!("0x{:x}", byte),
            0x08 => unimplemented!("0x{:x}", byte),
            0x09 => unimplemented!("0x{:x}", byte),
            0x0a => unimplemented!("0x{:x}", byte),
            0x0b => unimplemented!("0x{:x}", byte),
            0x0c => Some(Instruction::Inc(ArithmeticTarget::C)),
            0x0d => Some(Instruction::Dec(ArithmeticTarget::C)),
            0x0e => Some(Instruction::Load8(ArithmeticTarget::C)),
            0x0f => unimplemented!("0x{:x}", byte),
            0x10 => unimplemented!("0x{:x}", byte),
            0x11 => Some(Instruction::Load16(ArithmeticTarget::DE)),
            0x12 => unimplemented!("0x{:x}", byte),
            0x13 => unimplemented!("0x{:x}", byte),
            0x14 => Some(Instruction::Inc(ArithmeticTarget::D)),
            0x15 => Some(Instruction::Dec(ArithmeticTarget::D)),
            0x16 => unimplemented!("0x{:x}", byte),
            0x17 => unimplemented!("0x{:x}", byte),
            0x18 => unimplemented!("0x{:x}", byte),
            0x19 => unimplemented!("0x{:x}", byte),
            0x1a => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::DEH)), 
            0x1b => unimplemented!("0x{:x}", byte),
            0x1c => Some(Instruction::Inc(ArithmeticTarget::E)),
            0x1d => Some(Instruction::Dec(ArithmeticTarget::E)),
            0x1e => unimplemented!("0x{:x}", byte),
            0x1f => unimplemented!("0x{:x}", byte),
            0x20 => Some(Instruction::Jump(JumpTest::NotZero, JumpType::Relative8)),
            0x21 => Some(Instruction::Load16(ArithmeticTarget::HL)),
            0x22 => unimplemented!("0x{:x}", byte),
            0x23 => unimplemented!("0x{:x}", byte),
            0x24 => Some(Instruction::Inc(ArithmeticTarget::H)),
            0x25 => Some(Instruction::Dec(ArithmeticTarget::H)),
            0x26 => unimplemented!("0x{:x}", byte),
            0x27 => unimplemented!("0x{:x}", byte),
            0x28 => unimplemented!("0x{:x}", byte),
            0x29 => unimplemented!("0x{:x}", byte),
            0x2a => unimplemented!("0x{:x}", byte),
            0x2b => unimplemented!("0x{:x}", byte),
            0x2c => Some(Instruction::Inc(ArithmeticTarget::L)),
            0x2d => Some(Instruction::Dec(ArithmeticTarget::L)),
            0x2e => unimplemented!("0x{:x}", byte),
            0x2f => unimplemented!("0x{:x}", byte),
            0x30 => unimplemented!("0x{:x}", byte),
            0x31 => Some(Instruction::Load16(ArithmeticTarget::SP)),
            // TODO check meaning of HL-
            // decrease HL by 1
            // write position pointed by HL with content of A
            0x32 => Some(Instruction::Load(ArithmeticTarget::HLDec, ArithmeticTarget::A)),
            0x33 => unimplemented!("0x{:x}", byte),
            // TODO inc / dec for HL?
            0x34 => unimplemented!("0x{:x}", byte),
            0x35 => unimplemented!("0x{:x}", byte),
            0x36 => unimplemented!("0x{:x}", byte),
            0x37 => unimplemented!("0x{:x}", byte),
            0x38 => unimplemented!("0x{:x}", byte),
            0x39 => unimplemented!("0x{:x}", byte),
            0x3a => unimplemented!("0x{:x}", byte),
            0x3b => unimplemented!("0x{:x}", byte),
            0x3c => Some(Instruction::Inc(ArithmeticTarget::A)),
            0x3d => Some(Instruction::Dec(ArithmeticTarget::A)),
            0x3e => Some(Instruction::Load8(ArithmeticTarget::A)),
            0x3f => unimplemented!("0x{:x}", byte),
            0x40 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::B)),
            0x41 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::C)),
            0x42 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::D)),
            0x43 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::E)),
            0x44 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::H)),
            0x45 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::L)),
            // 0x46 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::HL)),
            0x47 => Some(Instruction::Load(ArithmeticTarget::B, ArithmeticTarget::A)),
            0x48 => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::B)),
            0x49 => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::C)),
            0x4a => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::D)),
            0x4b => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::E)),
            0x4c => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::H)),
            0x4d => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::L)),
            //0x4e => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::B)),
            0x4f => Some(Instruction::Load(ArithmeticTarget::C, ArithmeticTarget::A)),
            0x50 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::B)),
            0x51 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::C)),
            0x52 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::D)),
            0x53 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::E)),
            0x54 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::H)),
            0x55 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::L)),
            //0x56 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::B)),
            0x57 => Some(Instruction::Load(ArithmeticTarget::D, ArithmeticTarget::A)),
            0x58 => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::B)),
            0x59 => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::C)),
            0x5a => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::D)),
            0x5b => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::E)),
            0x5c => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::H)),
            0x5d => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::L)),
            //0x5e => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::B)),
            0x5f => Some(Instruction::Load(ArithmeticTarget::E, ArithmeticTarget::A)),
            0x60 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::B)),
            0x61 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::C)),
            0x62 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::D)),
            0x63 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::E)),
            0x64 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::H)),
            0x65 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::L)),
            //0x66 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::B)),
            0x67 => Some(Instruction::Load(ArithmeticTarget::H, ArithmeticTarget::A)),
            0x68 => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::B)),
            0x69 => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::C)),
            0x6a => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::D)),
            0x6b => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::E)),
            0x6c => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::H)),
            0x6d => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::L)),
            //0x6e => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::HL)),
            0x6f => Some(Instruction::Load(ArithmeticTarget::L, ArithmeticTarget::A)),
            0x70 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::B)),
            0x71 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::C)),
            0x72 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::D)),
            0x73 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::E)),
            0x74 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::H)),
            0x75 => Some(Instruction::Load(ArithmeticTarget::HL, ArithmeticTarget::L)),
            0x76 => Some(Instruction::Halt), 
            0x77 => Some(Instruction::Load(ArithmeticTarget::HLH, ArithmeticTarget::A)),
            0x78 => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::B)),
            0x79 => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::C)),
            0x7a => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::D)),
            0x7b => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::E)),
            0x7c => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::H)),
            0x7d => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::L)),
            0x7e => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::HL)),
            0x7f => Some(Instruction::Load(ArithmeticTarget::A, ArithmeticTarget::A)),
            // ADD
            0x80 => Some(Instruction::Add(ArithmeticTarget::B)),
            0x81 => Some(Instruction::Add(ArithmeticTarget::C)),
            0x82 => Some(Instruction::Add(ArithmeticTarget::D)),
            0x83 => Some(Instruction::Add(ArithmeticTarget::E)),
            0x84 => Some(Instruction::Add(ArithmeticTarget::H)),
            0x85 => Some(Instruction::Add(ArithmeticTarget::L)),
            //0x86 => Some(Instruction::Add(ArithmeticTarget::HL)),
            0x87 => Some(Instruction::Add(ArithmeticTarget::A)),
            // ADC
            0x88 => Some(Instruction::Adc(ArithmeticTarget::B)),
            0x89 => Some(Instruction::Adc(ArithmeticTarget::C)),
            0x8a => Some(Instruction::Adc(ArithmeticTarget::D)),
            0x8b => Some(Instruction::Adc(ArithmeticTarget::E)),
            0x8c => Some(Instruction::Adc(ArithmeticTarget::H)),
            0x8d => Some(Instruction::Adc(ArithmeticTarget::L)),
            //0x8e => Some(Instruction::Adc(ArithmeticTarget::HL)),
            0x8f => Some(Instruction::Adc(ArithmeticTarget::A)),
            // SUB
            0x90 => Some(Instruction::Sub(ArithmeticTarget::B)),
            0x91 => Some(Instruction::Sub(ArithmeticTarget::C)),
            0x92 => Some(Instruction::Sub(ArithmeticTarget::D)),
            0x93 => Some(Instruction::Sub(ArithmeticTarget::E)),
            0x94 => Some(Instruction::Sub(ArithmeticTarget::H)),
            0x95 => Some(Instruction::Sub(ArithmeticTarget::L)),
            //0x96 => Some(Instruction::Sub(ArithmeticTarget::HL)),
            0x97 => Some(Instruction::Sub(ArithmeticTarget::A)),
            // SBC
            0x98 => Some(Instruction::Sbc(ArithmeticTarget::B)),
            0x99 => Some(Instruction::Sbc(ArithmeticTarget::C)),
            0x9a => Some(Instruction::Sbc(ArithmeticTarget::D)),
            0x9b => Some(Instruction::Sbc(ArithmeticTarget::E)),
            0x9c => Some(Instruction::Sbc(ArithmeticTarget::H)),
            0x9d => Some(Instruction::Sbc(ArithmeticTarget::L)),
            //0x9e => Some(Instruction::Sbc(ArithmeticTarget::HL)),
            0x9f => Some(Instruction::Sbc(ArithmeticTarget::A)),
            // AND
            0xa0 => Some(Instruction::And(ArithmeticTarget::B)),
            0xa1 => Some(Instruction::And(ArithmeticTarget::C)),
            0xa2 => Some(Instruction::And(ArithmeticTarget::D)),
            0xa3 => Some(Instruction::And(ArithmeticTarget::E)),
            0xa4 => Some(Instruction::And(ArithmeticTarget::H)),
            0xa5 => Some(Instruction::And(ArithmeticTarget::L)),
            //0xa6 => Some(Instruction::And(ArithmeticTarget::HL)),
            0xa7 => Some(Instruction::And(ArithmeticTarget::A)),
            // XOR
            0xa8 => Some(Instruction::Xor(ArithmeticTarget::B)),
            0xa9 => Some(Instruction::Xor(ArithmeticTarget::C)),
            0xaa => Some(Instruction::Xor(ArithmeticTarget::D)),
            0xab => Some(Instruction::Xor(ArithmeticTarget::E)),
            0xac => Some(Instruction::Xor(ArithmeticTarget::H)),
            0xad => Some(Instruction::Xor(ArithmeticTarget::L)),
            0xae => Some(Instruction::Xor(ArithmeticTarget::HL)),
            0xaf => Some(Instruction::Xor(ArithmeticTarget::A)),
            // OR
            0xb0 => Some(Instruction::Or(ArithmeticTarget::B)),
            0xb1 => Some(Instruction::Or(ArithmeticTarget::C)),
            0xb2 => Some(Instruction::Or(ArithmeticTarget::D)),
            0xb3 => Some(Instruction::Or(ArithmeticTarget::E)),
            0xb4 => Some(Instruction::Or(ArithmeticTarget::H)),
            0xb5 => Some(Instruction::Or(ArithmeticTarget::L)),
            //0xb6 => Some(Instruction::Or(ArithmeticTarget::HL)),
            0xb7 => Some(Instruction::Or(ArithmeticTarget::A)),
            // CP
            0xb8 => Some(Instruction::Cp(ArithmeticTarget::B)),
            0xb9 => Some(Instruction::Cp(ArithmeticTarget::C)),
            0xba => Some(Instruction::Cp(ArithmeticTarget::D)),
            0xbb => Some(Instruction::Cp(ArithmeticTarget::E)),
            0xbc => Some(Instruction::Cp(ArithmeticTarget::H)),
            0xbd => Some(Instruction::Cp(ArithmeticTarget::L)),
            //0xbe => Some(Instruction::Cp(ArithmeticTarget::HL)),
            0xbf => Some(Instruction::Cp(ArithmeticTarget::A)),
            0xc0 => unimplemented!("0x{:x}", byte),
            0xc1 => unimplemented!("0x{:x}", byte),
            0xc2 => unimplemented!("0x{:x}", byte),
            0xc3 => unimplemented!("0x{:x}", byte),
            0xc4 => unimplemented!("0x{:x}", byte),
            0xc5 => Some(Instruction::Push(ArithmeticTarget::BC)), 
            0xc6 => unimplemented!("0x{:x}", byte),
            0xc7 => unimplemented!("0x{:x}", byte),
            0xc8 => unimplemented!("0x{:x}", byte),
            0xc9 => unimplemented!("0x{:x}", byte),
            0xca => unimplemented!("0x{:x}", byte),
            0xcb => unimplemented!("0x{:x}", byte),
            0xcc => unimplemented!("0x{:x}", byte),
            0xcd => Some(Instruction::Call(JumpTest::Always)),
            0xce => unimplemented!("0x{:x}", byte),
            0xcf => unimplemented!("0x{:x}", byte),
            0xd0 => unimplemented!("0x{:x}", byte),
            0xd1 => unimplemented!("0x{:x}", byte),
            0xd2 => unimplemented!("0x{:x}", byte),
            0xd3 => unimplemented!("0x{:x}", byte),
            0xd4 => unimplemented!("0x{:x}", byte),
            0xd5 => unimplemented!("0x{:x}", byte),
            0xd6 => unimplemented!("0x{:x}", byte),
            0xd7 => unimplemented!("0x{:x}", byte),
            0xd8 => unimplemented!("0x{:x}", byte),
            0xd9 => unimplemented!("0x{:x}", byte),
            0xda => unimplemented!("0x{:x}", byte),
            0xdb => unimplemented!("0x{:x}", byte),
            0xdc => unimplemented!("0x{:x}", byte),
            0xdd => unimplemented!("0x{:x}", byte),
            0xde => unimplemented!("0x{:x}", byte),
            0xdf => unimplemented!("0x{:x}", byte),
            0xe0 => Some(Instruction::LoadH8(ArithmeticTarget::A)),
            0xe1 => unimplemented!("0x{:x}", byte),
            0xe2 => Some(Instruction::LoadH(ArithmeticTarget::C, ArithmeticTarget::A)),
            0xe3 => unimplemented!("0x{:x}", byte),
            0xe4 => unimplemented!("0x{:x}", byte),
            0xe5 => unimplemented!("0x{:x}", byte),
            0xe6 => unimplemented!("0x{:x}", byte),
            0xe7 => unimplemented!("0x{:x}", byte),
            0xe8 => unimplemented!("0x{:x}", byte),
            0xe9 => unimplemented!("0x{:x}", byte),
            0xea => unimplemented!("0x{:x}", byte),
            0xeb => unimplemented!("0x{:x}", byte),
            0xec => unimplemented!("0x{:x}", byte),
            0xed => unimplemented!("0x{:x}", byte),
            0xee => unimplemented!("0x{:x}", byte),
            0xef => unimplemented!("0x{:x}", byte),
            0xf0 => unimplemented!("0x{:x}", byte),
            0xf1 => unimplemented!("0x{:x}", byte),
            0xf2 => unimplemented!("0x{:x}", byte),
            0xf3 => unimplemented!("0x{:x}", byte),
            0xf4 => unimplemented!("0x{:x}", byte),
            0xf5 => unimplemented!("0x{:x}", byte),
            0xf6 => unimplemented!("0x{:x}", byte),
            0xf7 => unimplemented!("0x{:x}", byte),
            0xf8 => unimplemented!("0x{:x}", byte),
            0xf9 => unimplemented!("0x{:x}", byte),
            0xfa => unimplemented!("0x{:x}", byte),
            0xfb => unimplemented!("0x{:x}", byte),
            0xfc => unimplemented!("0x{:x}", byte),
            0xfd => unimplemented!("0x{:x}", byte),
            0xfe => unimplemented!("0x{:x}", byte),
            0xff => unimplemented!("0x{:x}", byte),
            _ => None,
        }
    }

    pub fn from_prefixed_byte(byte: u8) -> Option<Instruction>{
        match byte {
            0x00 => unimplemented!("0x{:x}", byte),
            0x01 => unimplemented!("0x{:x}", byte),
            0x02 => unimplemented!("0x{:x}", byte),
            0x03 => unimplemented!("0x{:x}", byte),
            0x04 => unimplemented!("0x{:x}", byte),
            0x05 => unimplemented!("0x{:x}", byte),
            0x06 => unimplemented!("0x{:x}", byte),
            0x07 => unimplemented!("0x{:x}", byte),
            0x08 => unimplemented!("0x{:x}", byte),
            0x09 => unimplemented!("0x{:x}", byte),
            0x0a => unimplemented!("0x{:x}", byte),
            0x0b => unimplemented!("0x{:x}", byte),
            0x0c => unimplemented!("0x{:x}", byte),
            0x0d => unimplemented!("0x{:x}", byte),
            0x0e => unimplemented!("0x{:x}", byte),
            0x0f => unimplemented!("0x{:x}", byte),
            0x10 => unimplemented!("0x{:x}", byte),
            0x11 => Some(Instruction::Rl(ArithmeticTarget::C)),
            0x12 => unimplemented!("0x{:x}", byte),
            0x13 => unimplemented!("0x{:x}", byte),
            0x14 => unimplemented!("0x{:x}", byte),
            0x15 => unimplemented!("0x{:x}", byte),
            0x16 => unimplemented!("0x{:x}", byte),
            0x17 => unimplemented!("0x{:x}", byte),
            0x18 => unimplemented!("0x{:x}", byte),
            0x19 => unimplemented!("0x{:x}", byte),
            0x1a => unimplemented!("0x{:x}", byte),
            0x1b => unimplemented!("0x{:x}", byte),
            0x1c => unimplemented!("0x{:x}", byte),
            0x1d => unimplemented!("0x{:x}", byte),
            0x1e => unimplemented!("0x{:x}", byte),
            0x1f => unimplemented!("0x{:x}", byte),
            0x20 => unimplemented!("0x{:x}", byte),
            0x21 => unimplemented!("0x{:x}", byte),
            0x22 => unimplemented!("0x{:x}", byte),
            0x23 => unimplemented!("0x{:x}", byte),
            0x24 => unimplemented!("0x{:x}", byte),
            0x25 => unimplemented!("0x{:x}", byte),
            0x26 => unimplemented!("0x{:x}", byte),
            0x27 => unimplemented!("0x{:x}", byte),
            0x28 => unimplemented!("0x{:x}", byte),
            0x29 => unimplemented!("0x{:x}", byte),
            0x2a => unimplemented!("0x{:x}", byte),
            0x2b => unimplemented!("0x{:x}", byte),
            0x2c => unimplemented!("0x{:x}", byte),
            0x2d => unimplemented!("0x{:x}", byte),
            0x2e => unimplemented!("0x{:x}", byte),
            0x2f => unimplemented!("0x{:x}", byte),
            0x30 => Some(Instruction::Swap(ArithmeticTarget::B)),
            0x31 => Some(Instruction::Swap(ArithmeticTarget::C)),
            0x32 => Some(Instruction::Swap(ArithmeticTarget::D)),
            0x33 => Some(Instruction::Swap(ArithmeticTarget::E)),
            0x34 => Some(Instruction::Swap(ArithmeticTarget::H)),
            0x35 => Some(Instruction::Swap(ArithmeticTarget::L)),
            0x36 => Some(Instruction::Swap(ArithmeticTarget::HL)),
            0x37 => Some(Instruction::Swap(ArithmeticTarget::A)),
            0x38 => Some(Instruction::Srl(ArithmeticTarget::B)),
            0x39 => Some(Instruction::Srl(ArithmeticTarget::C)),
            0x3a => Some(Instruction::Srl(ArithmeticTarget::D)),
            0x3b => Some(Instruction::Srl(ArithmeticTarget::E)),
            0x3c => Some(Instruction::Srl(ArithmeticTarget::H)),
            0x3d => Some(Instruction::Srl(ArithmeticTarget::L)),
            0x3e => Some(Instruction::Srl(ArithmeticTarget::HL)),
            0x3f => Some(Instruction::Srl(ArithmeticTarget::A)),
            0x40 => Some(Instruction::Bit(ArithmeticTarget::B, 0)),
            0x41 => Some(Instruction::Bit(ArithmeticTarget::C, 0)),
            0x42 => Some(Instruction::Bit(ArithmeticTarget::D, 0)),
            0x43 => Some(Instruction::Bit(ArithmeticTarget::E, 0)),
            0x44 => Some(Instruction::Bit(ArithmeticTarget::H, 0)),
            0x45 => Some(Instruction::Bit(ArithmeticTarget::L, 0)),
            0x46 => Some(Instruction::Bit(ArithmeticTarget::HL, 0)),
            0x47 => Some(Instruction::Bit(ArithmeticTarget::A, 0)),
            0x48 => Some(Instruction::Bit(ArithmeticTarget::B, 1)),
            0x49 => Some(Instruction::Bit(ArithmeticTarget::C, 1)),
            0x4a => Some(Instruction::Bit(ArithmeticTarget::D, 1)),
            0x4b => Some(Instruction::Bit(ArithmeticTarget::E, 1)),
            0x4c => Some(Instruction::Bit(ArithmeticTarget::H, 1)),
            0x4d => Some(Instruction::Bit(ArithmeticTarget::L, 1)),
            0x4e => Some(Instruction::Bit(ArithmeticTarget::HL, 1)),
            0x4f => Some(Instruction::Bit(ArithmeticTarget::A, 1)),
            0x50 => Some(Instruction::Bit(ArithmeticTarget::B, 2)),
            0x51 => Some(Instruction::Bit(ArithmeticTarget::C, 2)),
            0x52 => Some(Instruction::Bit(ArithmeticTarget::D, 2)),
            0x53 => Some(Instruction::Bit(ArithmeticTarget::E, 2)),
            0x54 => Some(Instruction::Bit(ArithmeticTarget::H, 2)),
            0x55 => Some(Instruction::Bit(ArithmeticTarget::L, 2)),
            0x56 => Some(Instruction::Bit(ArithmeticTarget::HL, 2)),
            0x57 => Some(Instruction::Bit(ArithmeticTarget::A, 2)),
            0x58 => Some(Instruction::Bit(ArithmeticTarget::B, 3)),
            0x59 => Some(Instruction::Bit(ArithmeticTarget::C, 3)),
            0x5a => Some(Instruction::Bit(ArithmeticTarget::D, 3)),
            0x5b => Some(Instruction::Bit(ArithmeticTarget::E, 3)),
            0x5c => Some(Instruction::Bit(ArithmeticTarget::H, 3)),
            0x5d => Some(Instruction::Bit(ArithmeticTarget::L, 3)),
            0x5e => Some(Instruction::Bit(ArithmeticTarget::HL, 3)),
            0x5f => Some(Instruction::Bit(ArithmeticTarget::A, 3)),
            0x60 => Some(Instruction::Bit(ArithmeticTarget::B, 4)),
            0x61 => Some(Instruction::Bit(ArithmeticTarget::C, 4)),
            0x62 => Some(Instruction::Bit(ArithmeticTarget::D, 4)),
            0x63 => Some(Instruction::Bit(ArithmeticTarget::E, 4)),
            0x64 => Some(Instruction::Bit(ArithmeticTarget::H, 4)),
            0x65 => Some(Instruction::Bit(ArithmeticTarget::L, 4)),
            0x66 => Some(Instruction::Bit(ArithmeticTarget::HL, 4)),
            0x67 => Some(Instruction::Bit(ArithmeticTarget::A, 4)),
            0x68 => Some(Instruction::Bit(ArithmeticTarget::B, 5)),
            0x69 => Some(Instruction::Bit(ArithmeticTarget::C, 5)),
            0x6a => Some(Instruction::Bit(ArithmeticTarget::D, 5)),
            0x6b => Some(Instruction::Bit(ArithmeticTarget::E, 5)),
            0x6c => Some(Instruction::Bit(ArithmeticTarget::H, 5)),
            0x6d => Some(Instruction::Bit(ArithmeticTarget::L, 5)),
            0x6e => Some(Instruction::Bit(ArithmeticTarget::HL, 5)),
            0x6f => Some(Instruction::Bit(ArithmeticTarget::A, 5)),
            0x70 => Some(Instruction::Bit(ArithmeticTarget::B, 6)),
            0x71 => Some(Instruction::Bit(ArithmeticTarget::C, 6)),
            0x72 => Some(Instruction::Bit(ArithmeticTarget::D, 6)),
            0x73 => Some(Instruction::Bit(ArithmeticTarget::E, 6)),
            0x74 => Some(Instruction::Bit(ArithmeticTarget::H, 6)),
            0x75 => Some(Instruction::Bit(ArithmeticTarget::L, 6)),
            0x76 => Some(Instruction::Bit(ArithmeticTarget::HL, 6)),
            0x77 => Some(Instruction::Bit(ArithmeticTarget::A, 6)),
            0x78 => Some(Instruction::Bit(ArithmeticTarget::B, 7)),
            0x79 => Some(Instruction::Bit(ArithmeticTarget::C, 7)),
            0x7a => Some(Instruction::Bit(ArithmeticTarget::D, 7)),
            0x7b => Some(Instruction::Bit(ArithmeticTarget::E, 7)),
            0x7c => Some(Instruction::Bit(ArithmeticTarget::H, 7)),
            0x7d => Some(Instruction::Bit(ArithmeticTarget::L, 7)),
            0x7e => Some(Instruction::Bit(ArithmeticTarget::HL, 7)),
            0x7f => Some(Instruction::Bit(ArithmeticTarget::A, 7)),
            // Res
            0x80 => Some(Instruction::Res(ArithmeticTarget::B, 0)),
            0x81 => Some(Instruction::Res(ArithmeticTarget::C, 0)),
            0x82 => Some(Instruction::Res(ArithmeticTarget::D, 0)),
            0x83 => Some(Instruction::Res(ArithmeticTarget::E, 0)),
            0x84 => Some(Instruction::Res(ArithmeticTarget::H, 0)),
            0x85 => Some(Instruction::Res(ArithmeticTarget::L, 0)),
            0x86 => Some(Instruction::Res(ArithmeticTarget::HL, 0)),
            0x87 => Some(Instruction::Res(ArithmeticTarget::A, 0)),
            0x88 => Some(Instruction::Res(ArithmeticTarget::B, 1)),
            0x89 => Some(Instruction::Res(ArithmeticTarget::C, 1)),
            0x8a => Some(Instruction::Res(ArithmeticTarget::D, 1)),
            0x8b => Some(Instruction::Res(ArithmeticTarget::E, 1)),
            0x8c => Some(Instruction::Res(ArithmeticTarget::H, 1)),
            0x8d => Some(Instruction::Res(ArithmeticTarget::L, 1)),
            0x8e => Some(Instruction::Res(ArithmeticTarget::HL, 1)),
            0x8f => Some(Instruction::Res(ArithmeticTarget::A, 1)),
            0x90 => Some(Instruction::Res(ArithmeticTarget::B, 2)),
            0x91 => Some(Instruction::Res(ArithmeticTarget::C, 2)),
            0x92 => Some(Instruction::Res(ArithmeticTarget::D, 2)),
            0x93 => Some(Instruction::Res(ArithmeticTarget::E, 2)),
            0x94 => Some(Instruction::Res(ArithmeticTarget::H, 2)),
            0x95 => Some(Instruction::Res(ArithmeticTarget::L, 2)),
            0x96 => Some(Instruction::Res(ArithmeticTarget::HL, 2)),
            0x97 => Some(Instruction::Res(ArithmeticTarget::A, 2)),
            0x98 => Some(Instruction::Res(ArithmeticTarget::B, 3)),
            0x99 => Some(Instruction::Res(ArithmeticTarget::C, 3)),
            0x9a => Some(Instruction::Res(ArithmeticTarget::D, 3)),
            0x9b => Some(Instruction::Res(ArithmeticTarget::E, 3)),
            0x9c => Some(Instruction::Res(ArithmeticTarget::H, 3)),
            0x9d => Some(Instruction::Res(ArithmeticTarget::L, 3)),
            0x9e => Some(Instruction::Res(ArithmeticTarget::HL, 3)),
            0x9f => Some(Instruction::Res(ArithmeticTarget::A, 3)),
            0xa0 => Some(Instruction::Res(ArithmeticTarget::B, 4)),
            0xa1 => Some(Instruction::Res(ArithmeticTarget::C, 4)),
            0xa2 => Some(Instruction::Res(ArithmeticTarget::D, 4)),
            0xa3 => Some(Instruction::Res(ArithmeticTarget::E, 4)),
            0xa4 => Some(Instruction::Res(ArithmeticTarget::H, 4)),
            0xa5 => Some(Instruction::Res(ArithmeticTarget::L, 4)),
            0xa6 => Some(Instruction::Res(ArithmeticTarget::HL, 4)),
            0xa7 => Some(Instruction::Res(ArithmeticTarget::A, 4)),
            0xa8 => Some(Instruction::Res(ArithmeticTarget::B, 5)),
            0xa9 => Some(Instruction::Res(ArithmeticTarget::C, 5)),
            0xaa => Some(Instruction::Res(ArithmeticTarget::D, 5)),
            0xab => Some(Instruction::Res(ArithmeticTarget::E, 5)),
            0xac => Some(Instruction::Res(ArithmeticTarget::H, 5)),
            0xad => Some(Instruction::Res(ArithmeticTarget::L, 5)),
            0xae => Some(Instruction::Res(ArithmeticTarget::HL, 5)),
            0xaf => Some(Instruction::Res(ArithmeticTarget::A, 5)),
            0xb0 => Some(Instruction::Res(ArithmeticTarget::B, 6)),
            0xb1 => Some(Instruction::Res(ArithmeticTarget::C, 6)),
            0xb2 => Some(Instruction::Res(ArithmeticTarget::D, 6)),
            0xb3 => Some(Instruction::Res(ArithmeticTarget::E, 6)),
            0xb4 => Some(Instruction::Res(ArithmeticTarget::H, 6)),
            0xb5 => Some(Instruction::Res(ArithmeticTarget::L, 6)),
            0xb6 => Some(Instruction::Res(ArithmeticTarget::HL, 6)),
            0xb7 => Some(Instruction::Res(ArithmeticTarget::A, 6)),
            0xb8 => Some(Instruction::Res(ArithmeticTarget::B, 7)),
            0xb9 => Some(Instruction::Res(ArithmeticTarget::C, 7)),
            0xba => Some(Instruction::Res(ArithmeticTarget::D, 7)),
            0xbb => Some(Instruction::Res(ArithmeticTarget::E, 7)),
            0xbc => Some(Instruction::Res(ArithmeticTarget::H, 7)),
            0xbd => Some(Instruction::Res(ArithmeticTarget::L, 7)),
            0xbe => Some(Instruction::Res(ArithmeticTarget::HL, 7)),
            0xbf => Some(Instruction::Res(ArithmeticTarget::A, 7)),
            // set byte
            0xc0 => Some(Instruction::Set(ArithmeticTarget::B, 0)),
            0xc1 => Some(Instruction::Set(ArithmeticTarget::C, 0)),
            0xc2 => Some(Instruction::Set(ArithmeticTarget::D, 0)),
            0xc3 => Some(Instruction::Set(ArithmeticTarget::E, 0)),
            0xc4 => Some(Instruction::Set(ArithmeticTarget::H, 0)),
            0xc5 => Some(Instruction::Set(ArithmeticTarget::L, 0)),
            0xc6 => Some(Instruction::Set(ArithmeticTarget::HL, 0)),
            0xc7 => Some(Instruction::Set(ArithmeticTarget::A, 0)),
            0xc8 => Some(Instruction::Set(ArithmeticTarget::B, 1)),
            0xc9 => Some(Instruction::Set(ArithmeticTarget::C, 1)),
            0xca => Some(Instruction::Set(ArithmeticTarget::D, 1)),
            0xcb => Some(Instruction::Set(ArithmeticTarget::E, 1)),
            0xcc => Some(Instruction::Set(ArithmeticTarget::H, 1)),
            0xcd => Some(Instruction::Set(ArithmeticTarget::L, 1)),
            0xce => Some(Instruction::Set(ArithmeticTarget::HL, 1)),
            0xcf => Some(Instruction::Set(ArithmeticTarget::A, 1)),
            0xd0 => Some(Instruction::Set(ArithmeticTarget::B, 2)),
            0xd1 => Some(Instruction::Set(ArithmeticTarget::C, 2)),
            0xd2 => Some(Instruction::Set(ArithmeticTarget::D, 2)),
            0xd3 => Some(Instruction::Set(ArithmeticTarget::E, 2)),
            0xd4 => Some(Instruction::Set(ArithmeticTarget::H, 2)),
            0xd5 => Some(Instruction::Set(ArithmeticTarget::L, 2)),
            0xd6 => Some(Instruction::Set(ArithmeticTarget::HL, 2)),
            0xd7 => Some(Instruction::Set(ArithmeticTarget::A, 2)),
            0xd8 => Some(Instruction::Set(ArithmeticTarget::B, 3)),
            0xd9 => Some(Instruction::Set(ArithmeticTarget::C, 3)),
            0xda => Some(Instruction::Set(ArithmeticTarget::D, 3)),
            0xdb => Some(Instruction::Set(ArithmeticTarget::E, 3)),
            0xdc => Some(Instruction::Set(ArithmeticTarget::H, 3)),
            0xdd => Some(Instruction::Set(ArithmeticTarget::L, 3)),
            0xde => Some(Instruction::Set(ArithmeticTarget::HL, 3)),
            0xdf => Some(Instruction::Set(ArithmeticTarget::A, 3)),
            0xe0 => Some(Instruction::Set(ArithmeticTarget::B, 4)),
            0xe1 => Some(Instruction::Set(ArithmeticTarget::C, 4)),
            0xe2 => Some(Instruction::Set(ArithmeticTarget::D, 4)),
            0xe3 => Some(Instruction::Set(ArithmeticTarget::E, 4)),
            0xe4 => Some(Instruction::Set(ArithmeticTarget::H, 4)),
            0xe5 => Some(Instruction::Set(ArithmeticTarget::L, 4)),
            0xe6 => Some(Instruction::Set(ArithmeticTarget::HL, 4)),
            0xe7 => Some(Instruction::Set(ArithmeticTarget::A, 4)),
            0xe8 => Some(Instruction::Set(ArithmeticTarget::B, 5)),
            0xe9 => Some(Instruction::Set(ArithmeticTarget::C, 5)),
            0xea => Some(Instruction::Set(ArithmeticTarget::D, 5)),
            0xeb => Some(Instruction::Set(ArithmeticTarget::E, 5)),
            0xec => Some(Instruction::Set(ArithmeticTarget::H, 5)),
            0xed => Some(Instruction::Set(ArithmeticTarget::L, 5)),
            0xee => Some(Instruction::Set(ArithmeticTarget::HL, 5)),
            0xef => Some(Instruction::Set(ArithmeticTarget::A, 5)),
            0xf0 => Some(Instruction::Set(ArithmeticTarget::B, 6)),
            0xf1 => Some(Instruction::Set(ArithmeticTarget::C, 6)),
            0xf2 => Some(Instruction::Set(ArithmeticTarget::D, 6)),
            0xf3 => Some(Instruction::Set(ArithmeticTarget::E, 6)),
            0xf4 => Some(Instruction::Set(ArithmeticTarget::H, 6)),
            0xf5 => Some(Instruction::Set(ArithmeticTarget::L, 6)),
            0xf6 => Some(Instruction::Set(ArithmeticTarget::HL, 6)),
            0xf7 => Some(Instruction::Set(ArithmeticTarget::A, 6)),
            0xf8 => Some(Instruction::Set(ArithmeticTarget::B, 7)),
            0xf9 => Some(Instruction::Set(ArithmeticTarget::C, 7)),
            0xfa => Some(Instruction::Set(ArithmeticTarget::D, 7)),
            0xfb => Some(Instruction::Set(ArithmeticTarget::E, 7)),
            0xfc => Some(Instruction::Set(ArithmeticTarget::H, 7)),
            0xfd => Some(Instruction::Set(ArithmeticTarget::L, 7)),
            0xfe => Some(Instruction::Set(ArithmeticTarget::HL, 7)),
            0xff => Some(Instruction::Set(ArithmeticTarget::A, 7)),
            _ => None,
        }
    }
}


impl ToString for Instruction {
    fn to_string(&self) -> String {
        match self {
            Instruction::Nop => "nop",
            Instruction::Adc(_) => "adc", 
            Instruction::Add(_) => "add",
            Instruction::AddHL(_) => "addhl",
            Instruction::And(_) => "and",
            Instruction::Ccf(_) => "ccf",
            Instruction::Cp(_) => "cp", 
            Instruction::Cpl(_) => "cpl",
            Instruction::Dec(_) => "dec", 
            Instruction::Inc(_) => "inc",
            Instruction::Or(_) => "or",
            Instruction::Rla(_) => "rla",
            Instruction::Rlc(_) => "rlc",
            Instruction::Rl(_) => "rl",
            Instruction::Rr(_) => "rr", 
            Instruction::Rra(_) => "rra",
            Instruction::Rrc(_) => "rrc",
            Instruction::Rrca(_) => "rrca",
            Instruction::Rrla(_) => "rrla",
            Instruction::Sbc(_) => "sbc",
            Instruction::Scf(_) => "scf",
            Instruction::Sla(_) => "sla",
            Instruction::Sra(_) => "sra",
            Instruction::Srl(_) => "srl",
            Instruction::Sub(_) => "sub",
            Instruction::Swap(_) => "swap",
            Instruction::Xor(_) => "xor",
            Instruction::Load(_, _) => "load",
            Instruction::Load8(_) => "load8",
            Instruction::Load16(_) => "load16",
            Instruction::LoadH(_, _) => "loadh",
            Instruction::LoadH8(_) => "loadh8",
            Instruction::Jump(_, _) => "jump",
            Instruction::Push(_) => "push",
            Instruction::Pop(_) => "pop",
            Instruction::Call(_) => "call",
            Instruction::Ret(_) => "ret",
            Instruction::Bit(_, _) => "bit",
            Instruction::Set(_, _) => "set",
            Instruction::Res(_, _) => "res",
            Instruction::Halt => "halt",
        }.to_string()
    }
}