name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Task
      uses: arduino/setup-task@v2
    - name: Build
      run: cargo check --verbose
    - name: Clippy
      run: task clippy_check
    - name: Run tests
      run: task test
